### ISSUE TITLE
SIT installation process does NOT display warning nor offer to copy files when using base game installation location

### ISSUE THREAD

**Issue by Tahvohck** [stayintarkov/SIT.Manager.Avalonia#208]
The SIT installation documentation claims that manager versions after 2.0.8856.37884 will copy files to a new location, but this isn't happening while I try to install. I've had to manually copy the files myself.
![image](https://github.com/stayintarkov/SIT.Manager.Avalonia/assets/1668722/ecc238d8-d948-4747-a357-18e2d5a12fcc)
![image](https://github.com/stayintarkov/SIT.Manager.Avalonia/assets/1668722/e5569de9-d0c7-42bd-9ecc-7e5b3ee7631f)

**Comment by artehe** [comment]
It's because you'll have set the path to your SIT EFT install already.

It does work if the path isn't set and can be achieved by:
- Closing the manager
- Go to where you installed the manager and delete ManagerConfig.json
- Run the manager again and follow the install process then it will copy everything for you. 

This I think at least is somewhat more obvious in the current master branch but hasn't been released yet.
