### ISSUE TITLE
Linux settings appear to not be saving

### ISSUE THREAD

**Issue by Plootie** [stayintarkov/SIT.Manager.Avalonia#59]
Needs more investigation but it seems there is no manager config being saved to disk

**Comment by Plootie** [comment]
Not sure what was causing this but it resolved itself. I'm gonna close this as no-repro unless It happens again

**Comment by J0nathan550** [comment]
It may cause due security reasons of the Linux (path might be in inappropriate place or lacking time of saving the file)

For me for example, in Windows version sometimes launcher can forget my `username` and `password` data in `Play Page` because of ???

But after more clicking it will remember those values, not sure why it causing it tho. It can sometimes only save when my server is down, or not save at all when my server is up and I can play. Strange, code seems to be correct on that one.
