### ISSUE TITLE
Add ability to run server with specified IP inside of the "IP Address" box.

### ISSUE THREAD

**Issue by J0nathan550** [stayintarkov/SIT.Manager.Avalonia#68]
Main idea is to grab IP Address from the IP Box in `Play Page` rather than grabbing it from `http.json` it will be much easier to understand what IP will be used, and will remove confusion "why my server is down?"

**Comment by Plootie** [comment]
Thought over this for awhile and have decided not to implement this. This could lead to confusing behaviour itself and would break entirely once the play page is overhauled. I think it's best to continue parsing the `http.json` for the IP since as far as I'm aware that address should always work for connecting

**Comment by J0nathan550** [comment]
Same thoughts in here. I even forgot I opened this one.
